### ISSUE TITLE
Allow user to set shard length

### ISSUE THREAD

**Issue by ssgross** [googlegenomics/dataflow-java#24]
It seems like we used to have this feature, but now it's gone?  100,000bp is sometimes too small a length per shard.  Each request may end up getting a very small response.

**Comment by pgrosu** [comment]
Hi Sam,

I think you might have meant to post this in the following location - [under utils-java](https://github.com/googlegenomics/utils-java) - since the [Contig class](https://github.com/googlegenomics/utils-java/blob/master/src/main/java/com/google/cloud/genomics/utils/Contig.java) provides that setting:

https://github.com/googlegenomics/utils-java

Paul

**Comment by ssgross** [comment]
Paul,

Yes, I saw Contig has that setting, but there is no way to set it from the command-line AFAICT.  It seems when we run a dataflow we're always calling Contig's getShard() method with no arguments, which uses the default of 100,000bp per shard.

**Comment by pgrosu** [comment]
Hi Sam,

You are right, and you are free to always change the code with more features via a pull-request.  It will then be merged by Google after signing the CLA.

Hope it helps,
Paul

**Comment by pgrosu** [comment]
Hi Sam,

As you figured out, all you would need to do is change [line 43 in Contig.java](https://github.com/googlegenomics/utils-java/blob/master/src/main/java/com/google/cloud/genomics/utils/Contig.java#L43) to the following, by omitting the `final` keyword:

```java
public static long DEFAULT_NUMBER_OF_BASES_PER_SHARD = 100000;
```

Unfortunately I am not able to sign the CLA, so any changes I would make would not go through.

Hope it helps,
Paul

**Comment by deflaux** [comment]
Added as --basesPerShard=#
